name: Create feature docs
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-feature-docs:
    if: ${{ github.repository == 'alextheman231/eslint-plugin' }}
    uses: alextheman231/github-actions/.github/workflows/create-feature-docs.yml@f1ff1cf13a2143e1e04a55da4b1fd77c2adb9b78 # v14.0.0
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
