name: Create feature docs
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-feature-docs:
    if: ${{ github.repository == 'alextheman231/eslint-plugin' }}
    uses: alextheman231/github-actions/.github/workflows/create-feature-docs.yml@e4a092a202ca5bac12242bbf53a046f32a08455a # v10.4.0
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
