name: Create feature docs
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-feature-docs:
    if: ${{ github.repository == 'alextheman231/eslint-plugin' }}
    uses: alextheman231/github-actions/.github/workflows/create-feature-docs.yml@a8e567aa7146169f3d858752ffb0f2dfd9ecb70f # v14.0.1
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
